version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins
    privileged: true
    user: root
    container_name: jenkins
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - ./jenkins_home:/var/jenkins_home
      

    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml

    networks:
      - volansys-cicd

  postgresql:
    image: 'postgres:latest'
    user: root
    container_name: postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRES_USER=sonarqube
      - POSTGRES_DATABASE=sonarqube
      - POSTGRES_PASSWORD=sonarqube
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data

    networks:
      - volansys-cicd

  sonarqube:
    image: sonarqube:7.9-community
    container_name: sonarqube
    depends_on:
      - postgresql
    ports:
      - '9000:9000'
    environment:
       - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql:5432/sonarqube
       - SONARQUBE_JDBC_USERNAME=sonarqube
       - SONARQUBE_JDBC_PASSWORD=sonarqube
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

    networks:
      - volansys-cicd

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  jenkins_data:
  postgresql_data:

networks:
  volansys-cicd:
    driver: bridge

