#!/usr/bin/python

"""The first step is to create an SMTP object, each object is used for connection 
with one server."""

import smtplib
from email.MIMEMultipart import MIMEMultipart
from email.MIMEText import MIMEText
from email.MIMEBase import MIMEBase
from email import encoders
import datetime
import subprocess
import mysql.connector

### Create CSV File ###

d = datetime.date.today().strftime("%d_%b_%Y")
mydb = mysql.connector.connect(
  host="localhost",
  port="6533",
  user="admin",
  passwd="Admin@123",
  database="myDB"
)

mycursor = mydb.cursor()
cmd = "SELECT 'user_id', 'user_name', 'created_at' UNION ALL SELECT user_id, user_name, created_at FROM emargin_disclaimer INTO OUTFILE '/Database/data/CSV_Data/%s-emarginDetail.csv'    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"'   LINES TERMINATED BY '\n';" % (d)
cmdp = str(cmd)
mycursor.execute(cmdp)


### Send attached File ###

attach_file = "/Database/data/CSV_Data/%s-emarginDetail.csv" %d
attach = str(attach_file)


fromaddr = "ShankyAnky@gmail.com"
toaddr = ['abc@gmail.com','xyz@gmail.com']
cc = ['123@gmail.com','456@gmail.com']

toaddrs = toaddr + cc

msg = MIMEMultipart()

msg['From'] = fromaddr
msg['To'] = ", ".join(toaddr)
msg['Cc'] = ", ".join(cc)
msg['Subject'] = "Emargin Disclaimer on %s" %d

body = "Please find the attachment"

msg.attach(MIMEText(body, 'plain'))

filename = "%s-emarginDetail.csv" %d
attachment = open(attach, "rb")

part = MIMEBase('application', 'octet-stream')
part.set_payload((attachment).read())
encoders.encode_base64(part)
part.add_header('Content-Disposition', "attachment; filename= %s" % filename)
msg.attach(part)

server = smtplib.SMTP('192.168.102.72:2525')
server.ehlo()
text = msg.as_string()
server.sendmail(fromaddr, toaddrs, text)
#server.sendmail(msg['From'], ['To', 'Cc'], text)
server.quit()



